# Generated by Django 3.0.6 on 2020-07-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionNombres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'descripcion_nombres',
            },
        ),
    ]
