# Generated by Django 3.0.6 on 2020-07-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignoZodiaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'signo_zodiaco',
            },
        ),
        migrations.CreateModel(
            name='SignoCombNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_calculado', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('signo', models.ForeignKey(blank=True, db_column='signo', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_date.SignoZodiaco')),
            ],
            options={
                'db_table': 'signo_comb_num',
            },
        ),
    ]
