# Generated by Django 3.0.6 on 2020-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTirada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'configuraciones_tiradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaqueteCarta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cover', models.FileField(blank=True, null=True, upload_to='cartas/')),
                ('relacion_barajas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paquete_barajas',
                'managed': False,
            },
        ),
    ]
