# Generated by Django 3.0.6 on 2020-07-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='cartas/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carta',
            },
        ),
        migrations.CreateModel(
            name='CategoriaBasica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('elemento', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_simbolico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria_basica',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('valor_simbolico', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('significado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'numero',
            },
        ),
        migrations.CreateModel(
            name='TipoArcano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_arcano',
            },
        ),
        migrations.CreateModel(
            name='Descripciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.BooleanField(blank=True, null=True)),
                ('invertida', models.BooleanField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_carta', models.ForeignKey(blank=True, db_column='id_carta', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_tarot.Carta')),
            ],
            options={
                'db_table': 'descripcion',
            },
        ),
        migrations.AddField(
            model_name='carta',
            name='categoria_basica',
            field=models.ForeignKey(blank=True, db_column='categoria_basica', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_tarot.CategoriaBasica'),
        ),
        migrations.AddField(
            model_name='carta',
            name='color',
            field=models.ForeignKey(blank=True, db_column='color', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_tarot.Color'),
        ),
        migrations.AddField(
            model_name='carta',
            name='numero',
            field=models.ForeignKey(blank=True, db_column='numero', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_tarot.Numero'),
        ),
        migrations.AddField(
            model_name='carta',
            name='tipo_arcano',
            field=models.ForeignKey(blank=True, db_column='tipo_arcano', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_tarot.TipoArcano'),
        ),
    ]
